// HIP-only packed TurboQuant flash-attention template instances.

#include "../ggml-cuda/fattn-vec.cuh"

#define DECL_FATTN_VEC_TURBO_PAIR(type_K, type_V) \
    DECL_FATTN_VEC_CASE(128, type_K, type_V);      \
    DECL_FATTN_VEC_CASE(256, type_K, type_V);      \

DECL_FATTN_VEC_TURBO_PAIR(GGML_TYPE_TURBO3_0, GGML_TYPE_TURBO4_0)
DECL_FATTN_VEC_TURBO_PAIR(GGML_TYPE_TURBO4_0, GGML_TYPE_TURBO3_0)
DECL_FATTN_VEC_TURBO_PAIR(GGML_TYPE_Q8_0,     GGML_TYPE_TURBO3_0)
DECL_FATTN_VEC_TURBO_PAIR(GGML_TYPE_Q8_0,     GGML_TYPE_TURBO4_0)
DECL_FATTN_VEC_TURBO_PAIR(GGML_TYPE_TURBO3_0, GGML_TYPE_Q8_0)
DECL_FATTN_VEC_TURBO_PAIR(GGML_TYPE_TURBO4_0, GGML_TYPE_Q8_0)
