#pragma once

#include "llama.h"

#include <vector>

// t8 branch-2: two-signal pattern-window detector for the proactive exclusion
// of pattern-like (copy-mode) windows from the MTP(k1)->DFlash concat round.
// The concat round collapses when the confirmed window is a repetitive
// pattern (numbered lists, F1 letters): this header is the C++ port of the
// certified Python reference (workspace scripts/t8-b2-detector.py, semantics
// spec t8 Branch-2 sections 4.1-4.3) and MUST stay semantically identical to
// it - parity is certified by the fixture selftest (--spec-concat-selftest,
// gate G1 of the branch-2 plan; fixtures regenerated by the reference after
// every registered amendment of constants or semantics).
//
// Header-only, pure functions on token ids: no state, no allocation beyond
// the caller's vector, safe to call from any thread.
namespace spec_concat_exclusion {

// pre-registered detector parameters (spec t8 Branch-2 section 4.5) - these
// are amendable ONLY by the offline calibration, with the amendment recorded
// in the spec. Do NOT tune them to make a test pass.
constexpr int    W        = 16;  // minimum window: fewer tokens are never gated
constexpr int    P_MIN    = 2;   // smallest scanned lag
constexpr int    P_MAX    = 8;   // largest scanned lag (with W=16 a class reaches |C| >= 4 only for p <= 3)
constexpr double THETA_AC = 0.6; // AC threshold, STRICT comparison (score == 0.6 does NOT pass)
constexpr int    M        = 4;   // minimum size of a constant class

struct gating_result {
    bool        gated;
    const char * segnale; // "ac" | "classe" | "ac+classe", nullptr when not gated
};

// section 4.1: lag-p autocorrelation, match count over i in [p, n-1] with
// tokens[i] == tokens[i-p]. Returns 0 when n <= p (no valid comparison).
inline int score_ac_matches(const std::vector<llama_token> & tokens, int p) {
    const int n = (int) tokens.size();
    if (n <= p) {
        return 0;
    }
    int matches = 0;
    for (int i = p; i < n; ++i) {
        if (tokens[i] == tokens[i - p]) {
            matches++;
        }
    }
    return matches;
}

// section 4.1 as a score: score_ac_matches / (n - p). Double division exactly
// as the Python reference (matches / (n - p)). EXTERNAL DIAGNOSTICS ONLY:
// do NOT use this for gating decisions - the gating path below stays in
// integer arithmetic on purpose, and nothing at runtime may take a decision
// off the float surface.
inline double score_ac(const std::vector<llama_token> & tokens, int p) {
    const int n = (int) tokens.size();
    if (n <= p) {
        return 0.0;
    }
    return (double) score_ac_matches(tokens, p) / (double) (n - p);
}

// section 4.2: true if a constant class exists for some p in [P_MIN, P_MAX].
// Class at (p, r): every position i in [p, n-1] with i = r (mod p) matches
// (tokens[i] == tokens[i-p]) and the class has at least m positions. The scan
// starts at i = r + p, so the index r (r < p) is NOT in the class - its
// comparison tokens[r] vs tokens[r-p] is not valid.
inline bool has_constant_class(const std::vector<llama_token> & tokens, int m = M) {
    const int n = (int) tokens.size();
    for (int p = P_MIN; p <= P_MAX; ++p) {
        for (int r = 0; r < p; ++r) {
            int size = 0;
            for (int i = r + p; i < n; i += p) {
                size++;
            }
            if (size < m) {
                continue;
            }
            bool all_match = true;
            for (int i = r + p; i < n; i += p) {
                if (tokens[i] != tokens[i - p]) {
                    all_match = false;
                    break;
                }
            }
            if (all_match) {
                return true;
            }
        }
    }
    return false;
}

// section 4.3: the per-round verdict. Windows with fewer than W tokens are
// never gated; longer windows are evaluated whole (the caller passes exactly
// the last W confirmed tokens at runtime, but the contract evaluates any
// length as-is, never truncating). AC is active when score_ac exceeds
// THETA_AC STRICTLY for some p in [P_MIN, P_MAX].
//
// Arithmetic parity note (verified in the branch-2 plan review): the integer
// form score_ac_matches * 10 > (n - p) * 6 and the Python float form
// matches / (n - p) > 0.6 never diverge for any (matches, denominator) pair
// reachable under this window contract - checked exhaustively for every
// denominator up to w = 16, and beyond it both forms stay exact in the
// relevant range (all operands far below 2^53, boundary cases matches * 10 ==
// (n - p) * 6 round to the double literal 0.6 on the Python side, so both
// forms reject them identically). The integer form is used here on purpose.
inline gating_result gating(const std::vector<llama_token> & tokens) {
    const int n = (int) tokens.size();
    if (n < W) {
        return { false, nullptr };
    }

    bool ac = false;
    // the integer comparison below hard-codes theta 0.6 (as the 10/6 cross
    // multiply): a future amendment of THETA_AC must break this build instead
    // of letting the two forms diverge silently
    static_assert(THETA_AC == 0.6, "integer AC comparison hard-codes theta 0.6 - update match*10 > (n-p)*6 together with THETA_AC");
    for (int p = P_MIN; p <= P_MAX && !ac; ++p) {
        if (n <= p) {
            continue; // score 0.0, never above theta
        }
        ac = score_ac_matches(tokens, p) * 10 > (n - p) * 6;
    }
    const bool classe = has_constant_class(tokens);

    if (ac && classe) {
        return { true, "ac+classe" };
    }
    if (ac) {
        return { true, "ac" };
    }
    if (classe) {
        return { true, "classe" };
    }
    return { false, nullptr };
}

} // namespace spec_concat_exclusion
